### PR TITLE
Apply Scalafmt to `examples/` in CI

### PR DESCRIPTION
**Pull request by myyk**
Partially completes: #3829

Tested locally by breaking format of `example/scalalib/basic/1-simple/foo/src/Foo.scala` by just adding a bunch of spaces.

* Observe break with `./mill mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources` failure.
* Observe fix with `./mill mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources`

Used `// format: off` rather than changing [docstrings.style = keep](https://scalameta.org/scalafmt/docs/configuration.html#docstringsstyle--keep) to our `.scalafmt.conf` since that would affect all files. There doesn't seem to be a built in way in ScalaFmt to have folder level configs or something like this. I thought it might be better to not have `example` be an exception cases if we can avoid it. I'm not sure if the `// format: off` comments break something else though.

### CODE REVIEW

File: .scalafmt.conf [hunk 1]
```diff
@@ -20,4 +20,3 @@ newlines.source = keep
 project.git = true
 
 runner.dialect = scala213
-
```
Comment (lihaoyi) [inline .scalafmt.conf:23]: Let's bump the `version` to 3.8.4-RC1, that comes with support for recognizing `.mill` files.

Also, it seems like ScalaFmt does support per-glob overrides https://scalameta.org/scalafmt/docs/configuration.html#fileoverride, so I think we should be able to use that to enable `docstrings.style = keep` for `example/**/build.mill` without needing to enable it for the other Scala code

File: example/scalalib/linting/1-scalafmt/src/Foo.scala [hunk 2]
```diff
@@ -1,9 +1,4 @@
 package foo
-object Foo{
-def main(args:
-Array[String
-]
-):Unit=
-{println("hello world")
-}
+object Foo {
```
Comment (lihaoyi) [inline example/scalalib/linting/1-scalafmt/src/Foo.scala:2]: This file is meant to be mis-formatted, in order to exercise the Scalafmt workflow as part of the test suite. You should be able to skip the file specifically in `project.excludePaths` I think

**Comment by lihaoyi** [comment]
Looks great as a first pass, some config tweaks would allow us to include the `.mill` files and disable the comment formatting for those in `example/`, which would allow us to skip the `// format: off` comment in each one necessary to preserve the magic usage comments

**Comment by myyk** [comment]
After rebasing main, got this interesting new error. Also exists without `v3.8.4-RC1` change.
```
[903] parsed config (v3.8.4-RC1): /home/myyk/workspace/mill/myyk/mill/.scalafmt.conf
[903] error: /home/myyk/workspace/mill/myyk/mill/example/scalalib/native/1-simple/src/Foo.scala: org.scalafmt.dynamic.exceptions.PositionExceptionImpl: /home/myyk/workspace/mill/myyk/mill/example/scalalib/native/1-simple/src/Foo.scala:9: error: [dialect scala213] `:` expected but `identifier` found
[903]   def generateHtml(text: String) (using Zone) = {
[903]                                         ^
[903] Caused by: /home/myyk/workspace/mill/myyk/mill/example/scalalib/native/1-simple/src/Foo.scala:9: error: [dialect scala213] `:` expected but `identifier` found
[903]   def generateHtml(text: String) (using Zone) = {
[903]                                         ^
[903] 	at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$2(Scalafmt.scala:114)
[903] 	at scala.meta.parsers.Parsed.fold(Errors.scala:12)
[903] 	at scala.meta.parsers.Parsed.fold$(Errors.scala:10)
[903] 	at scala.meta.parsers.Parsed$Error.fold(Errors.scala:28)
[903] 	at org.scalafmt.Scalafmt$.doFormatOne(Scalafmt.scala:117)
[903] 	at org.scalafmt.Scalafmt$.doFormat(Scalafmt.scala:93)
[903] 	at org.scalafmt.Scalafmt$.$anonfun$formatCode$3(Scalafmt.scala:81)
[903] 	at scala.util.Success.fold(Try.scala:289)
[903] 	at org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:81)
[903] 	at org.scalafmt.Scalafmt$.format(Scalafmt.scala:60)
[903] 	at org.scalafmt.Scalafmt.format(Scalafmt.scala)
[903] 	at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
[903] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[903] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[903] 	at org.scalafmt.dynamic.ScalafmtReflect.$anonfun$tryFormat$1(ScalafmtReflect.scala:114)
[903] 	at scala.util.Try$.apply(Try.scala:217)
[903] 	at org.scalafmt.dynamic.ScalafmtReflect.tryFormat(ScalafmtReflect.scala:110)
[903] 	at org.scalafmt.dynamic.ScalafmtReflectConfig.tryFormat(ScalafmtReflectConfig.scala:91)
[903] 	at org.scalafmt.dynamic.ScalafmtDynamicSession.$anonfun$tryForceFormat$1(ScalafmtDynamicSession.scala:44)
[903] 	at scala.util.Success.flatMap(Try.scala:266)
[903] 	at org.scalafmt.dynamic.ScalafmtDynamicSession.tryForceFormat(ScalafmtDynamicSession.scala:44)
[903] 	at org.scalafmt.dynamic.ScalafmtDynamicSession.tryFormat(ScalafmtDynamicSession.scala:34)
[903] 	at org.scalafmt.dynamic.ScalafmtDynamicSession.format(ScalafmtDynamicSession.scala:19)
[903] 	at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:49)
[903] 	at mill.scalalib.scalafmt.ScalafmtWorker.$anonfun$reformatAction$2(ScalafmtWorker.scala:75)
[903] 	at scala.collection.immutable.VectorStatics$.foreachRec(Vector.scala:2125)
[903] 	at scala.collection.immutable.Vector.foreach(Vector.scala:2131)
[903] 	at mill.scalalib.scalafmt.ScalafmtWorker.reformatAction(ScalafmtWorker.scala:73)
[903] 	at mill.scalalib.scalafmt.ScalafmtWorker.checkFormat(ScalafmtWorker.scala:27)
[903] 	at mill.scalalib.scalafmt.ScalafmtModule$.$anonfun$checkFormatAll$1(ScalafmtModule.scala:91)
[903] 	at mill.define.Task$TraverseCtx.evaluate(Task.scala:215)
[903] 	at mill.eval.GroupEvaluator.$anonfun$evaluateGroup$10(GroupEvaluator.scala:308)
[903] 	at mill.eval.GroupEvaluator.$anonfun$evaluateGroup$9(GroupEvaluator.scala:302)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$6(SystemStreams.scala:100)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$5(SystemStreams.scala:99)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$4(SystemStreams.scala:98)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at scala.Console$.withErr(Console.scala:193)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$3(SystemStreams.scala:97)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at scala.Console$.withOut(Console.scala:164)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$2(SystemStreams.scala:96)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at scala.Console$.withIn(Console.scala:227)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$1(SystemStreams.scala:95)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at mill.api.SystemStreams$.withStreams(SystemStreams.scala:94)
[903] 	at mill.eval.GroupEvaluator.$anonfun$evaluateGroup$8(GroupEvaluator.scala:299)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at mill.eval.GroupEvaluator.wrap$1(GroupEvaluator.scala:298)
[903] 	at mill.eval.GroupEvaluator.$anonfun$evaluateGroup$3(GroupEvaluator.scala:307)
[903] 	at mill.eval.GroupEvaluator.$anonfun$evaluateGroup$3$adapted(GroupEvaluator.scala:256)
[903] 	at scala.collection.immutable.Vector.foreach(Vector.scala:2125)
[903] 	at mill.eval.GroupEvaluator.computeAll$1(GroupEvaluator.scala:256)
[903] 	at mill.eval.GroupEvaluator.evaluateGroup(GroupEvaluator.scala:334)
[903] 	at mill.eval.GroupEvaluator.$anonfun$evaluateGroupCached$1(GroupEvaluator.scala:202)
[903] 	at mill.api.Logger.withPrompt(Logger.scala:83)
[903] 	at mill.api.Logger.withPrompt$(Logger.scala:81)
[903] 	at mill.util.PrefixLogger.withPrompt(PrefixLogger.scala:7)
[903] 	at mill.eval.GroupEvaluator.evaluateGroupCached(GroupEvaluator.scala:67)
[903] 	at mill.eval.GroupEvaluator.evaluateGroupCached$(GroupEvaluator.scala:47)
[903] 	at mill.eval.EvaluatorImpl.evaluateGroupCached(EvaluatorImpl.scala:16)
[903] 	at mill.eval.EvaluatorCore.$anonfun$evaluate0$2(EvaluatorCore.scala:163)
[903] 	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
[903] 	at mill.eval.ExecutionContexts$ThreadPool$$anon$1.$anonfun$run$3(ExecutionContexts.scala:69)
[903] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$6(SystemStreams.scala:100)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$5(SystemStreams.scala:99)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$4(SystemStreams.scala:98)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at scala.Console$.withErr(Console.scala:193)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$3(SystemStreams.scala:97)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at scala.Console$.withOut(Console.scala:164)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$2(SystemStreams.scala:96)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at scala.Console$.withIn(Console.scala:227)
[903] 	at mill.api.SystemStreams$.$anonfun$withStreams$1(SystemStreams.scala:95)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at mill.api.SystemStreams$.withStreams(SystemStreams.scala:94)
[903] 	at mill.eval.ExecutionContexts$ThreadPool$$anon$1.$anonfun$run$2(ExecutionContexts.scala:69)
[903] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[903] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[903] 	at mill.eval.ExecutionContexts$ThreadPool$$anon$1.run(ExecutionContexts.scala:68)
[903] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[903] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[903] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[903] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[903] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

File: example/scalalib/linting/1-scalafmt/src/Foo.scala (hunk 2 above)
Comment (myyk) [reply example/scalalib/linting/1-scalafmt/src/Foo.scala]: Oh, good catch. Fixed.

**Comment by lihaoyi** [comment]
@myyk ah that's the parser not liking the Scala 3 syntax used in that file. I think you should be able to just skip those files, or use fileOverride config to tell ScalaFmt to use Scala 3 syntax

File: .scalafmt.conf (hunk 1 above)
Comment (myyk) [reply .scalafmt.conf:23]: Oh nice, I didn't quickly find how to apply file overrides like that! Thanks!

File: scalalib/test/src/mill/scalalib/TestModuleUtilTests.scala [hunk 3]
```diff
@@ -254,6 +254,7 @@ object TestModuleUtilTests extends TestSuite {
         )
       )
     }
+    // format: off
```
Comment (myyk) [inline scalalib/test/src/mill/scalalib/TestModuleUtilTests.scala:257]: I did this because it keeps fucking up the format inside this function. format didn't seem to turn off on a llne based usage.

**Comment by myyk** [comment]
@lihaoyi I applied all the feedback given. I'm much happier with this version.

File: scalalib/test/src/mill/scalalib/TestModuleUtilTests.scala (hunk 3 above)
Comment (lihaoyi) [reply scalalib/test/src/mill/scalalib/TestModuleUtilTests.scala:257]: Sounds good, maybe something to do with the XML literals which are pretty obscure and mayb the formatter doesn't work well with

**Review by lihaoyi — APPROVED** [review]
Looks good to me, CC @lefou  in case you want to review this before we merge it
