### PR TITLE
Android: Fix resource linking on multimodule projects

### PR DESCRIPTION
**Pull request by souvlakias**
Addresses #6237
 
This is a temporary fix for the resource linking until we properly pass submodules' resources to other modules.
 
### Changes
- Set the `--non-final-ids` flag in aapt2 link call for non-app modules
- Pass  recursiveModuleDeps' namespaces as `--extra-packages` to aapt
- Pickup all java files from `androidLinkedResources` instead of only R.java
- Set `kotlincUseBtApi` to false in `AndroidHiltSupport` ([Ref](https://github.com/com-lihaoyi/mill/issues/6355#issuecomment-3636550819))

### CODE REVIEW

File: libs/androidlib/src/mill/androidlib/AndroidModule.scala [hunk 1]
```diff
@@ -131,15 +131,23 @@ trait AndroidModule extends JavaModule { outer =>
...
-      )
-    } else {
-      Seq("--auto-add-overlay")
-    }
+    val debugOptions = Seq(
+      "--proguard-minimal-keep-rules",
+      "--debug-mode"
+    )
+
+    // Add module dependencies' namespaces as extra packages
```
Comment (vaslabs) [inline libs/androidlib/src/mill/androidlib/AndroidModule.scala]: We should add a TODO here to clean up, once we rewire the submodule sources to go to the app module

File: libs/androidlib/src/mill/androidlib/AndroidModule.scala [hunk 2]
```diff
@@ -498,7 +506,8 @@ trait AndroidModule extends JavaModule { outer =>
     // * it will generate R.java for the library even library has no resources declared
     // * R.java will have not only resource ID from this library, but from other libraries as well. They should be stripped.
     val rClassDir = androidLinkedResources().path / "generatedSources/java"
-    val mainRClassPath = os.walk(rClassDir)
+    val javaSources = os.walk(rClassDir).filter(p => os.isFile(p) && p.ext == "java")
+    val mainRClassPath = javaSources
```
Comment (vaslabs) [inline libs/androidlib/src/mill/androidlib/AndroidModule.scala]: can rename this to rSources

File: example/androidlib/java/1-hello-world/build.mill [hunk 3]
```diff
@@ -99,7 +99,7 @@ object app extends AndroidAppModule {
 /** Usage
 
 > ./mill show app.test
-...compiling 1 Java source...
+...compiling 2 Java sources to out/app/test/compile.dest/classes...
```
Comment (souvlakias) [inline example/androidlib/java/1-hello-world/build.mill:102]: This was intended to match for the `compile` task and should have failed when we defaulted BuildConfig to true in #6145 as a second source was being added, but it coincidentaly matched with the `androidCompiledRClasses`
> compiling 1 Java sources to out/app/test/androidCompiledRClasses.dest/classes

Now we explicitly match for the `compile` task

**Comment by vaslabs** [comment]
the androidtodo does not seem to be working with the changes

```
8106]   Test com.example.android.architecture.blueprints.todoapp.taskdetail.TaskDetailViewModelTest.activateTask 
failed: java.lang.NoClassDefFoundError: com/example/android/architecture/blueprints/todoapp/R$string, took 0.072 sec
```

**Comment by vaslabs** [comment]
pokemon multimodule is also complaining:

```
Error: Missing class com.nicos.compose_ui.R$color (referenced from: int com.nicos.compose_ui.utils.extensions.ExtensionsKt.colorToInt$default(android.graphics.drawable.Drawable, android.content.Context, int, int, java.lang.Object))
599] Missing class com.nicos.compose_ui.R$drawable (referenced from: kotlin.Unit com.nicos.compose_ui.components.ToolbarKt.CustomToolbar_3IgeMak$lambda$8(kotlin.jvm.functions.Function0, androidx.compose.runtime.Composer, int))
599] Missing class com.nicos.compose_ui.R$string (referenced from: kotlin.Unit com.nicos.compose_ui.components.ComposableSingletons$GenericViewsKt.lambda__515675410$lambda$0(androidx.compose.foundation.layout.RowScope, androidx.compose.runtime.Composer, int) and 4 other contexts)
599] Missing class com.nicos.network.R$string (referenced from: java.lang.String com.nicos.network.generic_classes.HandlingError.handleErrorMessage(java.lang.Throwa
```

**Comment by vaslabs** [comment]
I think we need transitive modules instead

File: libs/androidlib/src/mill/androidlib/AndroidModule.scala [hunk 4]
```diff
@@ -131,15 +131,24 @@ trait AndroidModule extends JavaModule { outer =>
...
-      Seq("--auto-add-overlay")
-    }
+    val debugOptions = Seq(
+      "--proguard-minimal-keep-rules",
+      "--debug-mode"
+    )
+
+    // Add module dependencies' namespaces as extra packages
+    // TODO: cleanup once we properly pass resources from dependencies
+    val extraPackages = moduleDeps.collect {
```
Comment (vaslabs) [inline libs/androidlib/src/mill/androidlib/AndroidModule.scala]: maybe here we need transitive modules.

Also for better customisation , we can make this into a task.

`androidAaptLinkExtraPackages`

File: libs/androidlib/src/mill/androidlib/AndroidAppModule.scala [hunk 5]
```diff
@@ -235,6 +235,10 @@ trait AndroidAppModule extends AndroidModule { outer =>
     )
   }
 
+  override def androidAaptOptions: T[Seq[String]] = Task {
+    super.androidAaptOptions().filterNot(_ == "--non-final-ids")
```
Comment (vaslabs) [inline libs/androidlib/src/mill/androidlib/AndroidAppModule.scala]: we should have a task androidAaptNonFinalIds instead, so we avoid filtering and append it [here](https://github.com/com-lihaoyi/mill/pull/6249/changes#diff-860dd1deac6289159d6fb5ae208aa73a654e2b39f0cda226b63cd920d443d1c7R149)



if it's set to true
