### ISSUE TITLE
Regression in scala.js linking

### ISSUE THREAD

**Issue by rockjam** [com-lihaoyi/mill#277]
For example in project https://github.com/antonkulaga/GEOmetadb-scala while running `mill web.client.fastOpt` on version above 0.1.7(need to find specific version) there is linking error involving missing `scala.xml.NodeBuffer.$$amp$plus` method. Stack trace: 

```
Linker: Compute reachability: 1305100 us
Referring to non-existent method scala.xml.NodeBuffer.$$amp$plus(java.lang.Object)scala.xml.NodeBuffer
  called from group.research.aging.geometa.web.MainJS$.dataRow(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$component$3(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$component$2(scala.collection.immutable.List)scala.collection.immutable.List
  called from group.research.aging.geometa.web.MainJS$.<init>()
  called from core module module initializers
involving instantiated classes:
  group.research.aging.geometa.web.MainJS$
    instantiated from core module module initializers
Referring to non-existent method scala.xml.NodeBuffer.$$amp$plus(java.lang.Object)scala.xml.NodeBuffer
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$dataRow$1(java.lang.String)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.dataRow(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$component$3(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$component$2(scala.collection.immutable.List)scala.collection.immutable.List
  called from group.research.aging.geometa.web.MainJS$.<init>()
  called from core module module initializers
involving instantiated classes:
  group.research.aging.geometa.web.MainJS$
    instantiated from core module module initializers
Referring to non-existent method scala.xml.Elem.<init>(java.lang.String,java.lang.String,scala.xml.MetaData,scala.xml.NamespaceBinding,scala.Boolean,scala.collection.Seq)
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$dataRow$1(java.lang.String)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.dataRow(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$component$3(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$component$2(scala.collection.immutable.List)scala.collection.immutable.List
  called from group.research.aging.geometa.web.MainJS$.<init>()
  called from core module module initializers
involving instantiated classes:
  group.research.aging.geometa.web.MainJS$
    instantiated from core module module initializers
Referring to non-existent method scala.xml.Elem.<init>(java.lang.String,java.lang.String,scala.xml.MetaData,scala.xml.NamespaceBinding,scala.Boolean,scala.collection.Seq)
  called from group.research.aging.geometa.web.MainJS$.dataRow(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$component$3(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$component$2(scala.collection.immutable.List)scala.collection.immutable.List
  called from group.research.aging.geometa.web.MainJS$.<init>()
  called from core module module initializers
involving instantiated classes:
  group.research.aging.geometa.web.MainJS$
    instantiated from core module module initializers
Referring to non-existent method scala.xml.NodeBuffer.$$amp$plus(java.lang.Object)scala.xml.NodeBuffer
  called from group.research.aging.geometa.web.MainJS$.header(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$component$1(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.<init>()
  called from core module module initializers
involving instantiated classes:
  group.research.aging.geometa.web.MainJS$
    instantiated from core module module initializers
Referring to non-existent method scala.xml.NodeBuffer.$$amp$plus(java.lang.Object)scala.xml.NodeBuffer
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$header$1(java.lang.String)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.header(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.$$anonfun$component$1(scala.collection.immutable.List)scala.xml.Elem
  called from group.research.aging.geometa.web.MainJS$.<init>()
  called from core module module initializers
involving instantiated classes:
  group.research.aging.geometa.web.MainJS$
    instantiated from core module module initializers
```

Seems that this regression is introduced in 25b321ea9431590d5852366585f1691717651fea , need to investigate it further

**Comment by rockjam** [comment]
I think that it broke in 25b321ea9431590d5852366585f1691717651fea cause in a4713c3842c91a914cbc0ccd1f57339fa030f676 linking works fine

**Comment by antonkulaga** [comment]
0.1.7 looks fine, the problem is in master

**Comment by lihaoyi** [comment]
I can't even get past compilation on the latest Mill master without an error:

```scala
lihaoyi GEOmetadb-scala$ ../../Github/mill/out/dev/launcher/dest/run web.client.fastOpt
[66/75] web.client.compile
[info] Compiling 12 Scala sources to /Users/lihaoyi/Dropbox/Workspace/GEOmetadb-scala/out/web/client/compile/dest/classes ...
[error] /Users/lihaoyi/Dropbox/Workspace/GEOmetadb-scala/web/client/src/group/research/aging/geometa/web/QueryView.scala:39:8: overloaded method constructor UnprefixedAttribute with alternatives:
[error]   (key: String,value: Option[Seq[scala.xml.Node]],next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: String,next: scala.xml.MetaData)scala.xml.UnprefixedAttribute <and>
[error]   (key: String,value: Seq[scala.xml.Node],next1: scala.xml.MetaData)scala.xml.UnprefixedAttribute
[error]  cannot be applied to (String, scala.scalajs.js.Dynamic => Unit, scala.xml.MetaData)
[error]       <button class={ enabledIf("ui primary button", speciesToChoose) } onclick = { updateClick(toLoad, Search.empty) }>Search</button>
[error]        ^
[error] one error found
1 targets failed
web.client.compile Compilation failed
```

**Comment by antonkulaga** [comment]
Any progress on this? I keep getting this problem in Mill 0.2.0

**Comment by rockjam** [comment]
@antonkulaga Not really. As I said - I tried to reproduce it, and sometimes it happens, sometimes everything is fine.

**Comment by antonkulaga** [comment]
It is a blocker for me :-( It ties me to the old Mill version Maybe it is possible to check what changed between last working version and last broken version? I think you did something about caching or similar there

**Comment by antonkulaga** [comment]
```
java.nio.file.NoSuchFileException: /home/antonkulaga/.mill/ammonite/rt-10.0.1.jar
```

**Comment by rockjam** [comment]
@antonkulaga did you build it with java 9? can you try to build it with java 8?

**Comment by antonkulaga** [comment]
It was java10, Ok I will try to test old mill with java8 (mill 2.0 works well with java10).
Actually, the bug is quite easy to reproduce for me with mill 2.0
```bash
git clone https://github.com/antonkulaga/GEOmetadb-scala
cd GEOmetadb-scala
mill mill.scalalib.GenIdea/idea
```

**Comment by antonkulaga** [comment]
@rockjam  I managed to build with 25b321ea9431590d5852366585f1691717651fea and GenIdeaModule seemed to work. Will use it for one more day to see if it crashes anywhere (for mill 2 crash with mill mill.scalalib.GenIdea/idea is very reliable for me, but for that commit mill mill.scalalib.GenIdeaModule/idea did not lead to the crash)

**Comment by antonkulaga** [comment]
I've just checked with mill 0.2.2, the bug is still there (while https://github.com/lihaoyi/mill/commit/25b321ea9431590d5852366585f1691717651fea works fine) and it 100% reproducible with mill mill.scalalib.GenIdea/idea (at least on my machine).

**Comment by raskam** [comment]
While trying to port SBT project to Mill, I've just encountered the same issue with Mill 0.2.4 on Java 8. It seems to me that Mill is trying to link JVM libs instead of Scala.js ones.

Int the following example, the Scala.js implementation of `Instant.toString` does not use `DateTimeFormatter` (see https://github.com/scala-js/scala-js-java-time/blob/master/src/main/scala/java/time/Instant.scala), so it must be taken from JVM libs...

```
> mill FrontendModule.fastOpt 1>/dev/null
[212/212] FrontendModule.fastOpt
Referring to non-existent method java.util.Locale$.getDefault()java.util.Locale
  called from java.time.format.DateTimeFormatterBuilder.toFormatter()java.time.format.DateTimeFormatter
  called from java.time.format.DateTimeFormatterBuilder.toFormatter(java.time.format.ResolverStyle)java.time.format.DateTimeFormatter
  called from java.time.format.DateTimeFormatter$.<init>()
  called from java.time.Instant.toString()java.lang.String
  called from scalacss.internal.Percentage.value()java.lang.String
  called from scalacss.internal.ValueT$Rules.$$anonfun$rulePct$undP$1(scalacss.internal.Percentage)java.lang.String
  called from scalacss.internal.ValueT$Rules.rulePct$undP()scalacss.internal.ValueT$Rule
  called from <redacted>
  called from core module module initializers
involving instantiated classes:
  java.time.format.DateTimeFormatterBuilder
  java.time.Instant
  scalacss.internal.Percentage
  scalacss.internal.mutable.StyleSheet$Base$dsl$
  scalacss.internal.Dsl$
  <redacted>
1 targets failed
FrontendModule.fastOpt There were linking errors
```

**Comment by antonkulaga** [comment]
the bug is still valid with 0.26

**Comment by bbarker** [comment]
@antonkulaga so I checked out your repo (after noticing one of my own monadic-html repos seemed to compile with fastOpt) and it semes to build; just to confirm, I assume this issue is only happening on Java 10 for you atm? I'm still a dinosaur stuck with Java 8. Though I'm not sure why @raskam has issues with Java 8.

**Comment by raskam** [comment]
@bbarker Maybe my issue was related to something else (probably corrupt caches) as I don't remember experiencing it again while testing mill.

**Comment by antonkulaga** [comment]
@raskam the behavior of the bug changed for me with the latest Mill, now it often cannot find parts of scala.xml published inside monadic.html.

**Comment by lefou** [comment]
Is this still an issue? Or can we close this ticket?

**Comment by raskam** [comment]
@lefou I cannot test it on my side anymore as we did not adopt Mill in the end.

**Comment by lefou** [comment]
Closing, as this is most likely no longer relevant.
