### PR TITLE
Allow `Cross` module types to be traits for greater regularity and less boilerplate at callsite

### PR DESCRIPTION
**Pull request by lihaoyi**
### Concise Cross-Module Definition

This PR lets you replace the existing cross-module syntax using `class`es:

```scala
object bar extends Cross[BarModule](scalaVersions:_*)
class BarModule(val crossScalaVersion: String) extends MyCrossScalaModule{
  def moduleDeps = Seq(qux)
}
```

With a new lighter-weight variant:

```scala
object bar extends Cross[BarModule](scalaVersions)
trait BarModule extends MyCrossScalaModule{
  def moduleDeps = Seq(qux)
}
```

Furthermore, passing in the wrong type of keys to `Cross` is now a compile error, rather than blowing up at runtime with a stacktrace:

```
  java.lang.ExceptionInInitializerError
    mill.define.BasePathTests$.$anonfun$tests$16(BasePathTests.scala:39)
    mill.define.BasePathTests$.checkMillSourcePath$1(BasePathTests.scala:10)
    mill.define.BasePathTests$.$anonfun$tests$15(BasePathTests.scala:39)
  java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
    mill.util.TestGraphs$singleCross$cross$$anonfun$$lessinit$greater$1.apply(TestGraphs.scala:222)
    mill.define.Cross.$anonfun$items$1(Cross.scala:104)
    scala.collection.immutable.List.map(List.scala:250)
    mill.define.Cross.<init>(Cross.scala:92)
    mill.util.TestGraphs$singleCross$cross$.<init>(TestGraphs.scala:222)
    mill.util.TestGraphs$singleCross$cross$.<clinit>(TestGraphs.scala:222)
    mill.define.BasePathTests$.$anonfun$tests$16(BasePathTests.scala:39)
    mill.define.BasePathTests$.checkMillSourcePath$1(BasePathTests.scala:10)
    mill.define.BasePathTests$.$anonfun$tests$15(BasePathTests.scala:39)
```

We get a compile error with a nice position and error message

```scala
[error] /Users/lihaoyi/Github/mill/main/test/src/mill/util/TestGraphs.scala:222:44: type mismatch;
[error]  found   : Int
[error]  required: String
[error]     object cross extends mill.Cross[Cross](210, "211", "212")
[error]                                            ^
[error] one error found
```

We now require that all `Cross[T]` types `T` are traits inheriting from `Cross.Module[V]`, and expose `crossValue: V` in the body of the traits for usage. While for one-off cross `trait`s this is just as verbose as the status quo, the fact that you can hide the `Cross.Module[V]` on some base traits such as `CrossScalaModule` means that you don't need to repeat it on ever cross-module you instantiate, which is a big win.

### Improved type safety 

The `Cross` overhaul in this PR also makes it possible to provide static errors when the cross-type is invalid:

```scala
TestGraphs.scala:235:60: could not find implicit value for evidence parameter of type mill.define.Cross.ToSegments[sun.misc.Unsafe]
[error]     object cross extends mill.Cross[Cross](210.asInstanceOf[sun.misc.Unsafe])
[error]                                                            ^
```

This previously would crash with confusing stack traces at runtime

### Support for non-string Cross Types

Furthermore, you can properly define cross-modules that take other non-string types as keys:

```scala
  object nonStringCross extends TestUtil.BaseModule {
    object cross extends mill.Cross[Cross](210, 211, 212)
    trait Cross extends Cross.Module[Int] {
      def suffix = T { crossValue }
    }

    object cross2 extends mill.Cross[Cross2](210L, 211L, 212L)
    trait Cross2 extends Cross.Module[Long] {
      override def millSourcePath = super.millSourcePath / crossValue.toString
      def suffix = T { crossValue }
    }
  }
```

Non-string keys were previously half-supported in Mill: you could depend on these cross-modules in your build, but you could not reference them from the command line. Now, they work as expected, using the `Cross.ToSegments` typeclass to convert them to strings that you can reference from the command line.

### Extensibility

Multi-dimensional cross modules can be created via the `Cross.Module2` trait:

```scala
object myCross2 extends Cross[MyCrossModule2](("a", 1), ("b", 2))
trait MyCrossModule2 extends Cross.Module2[String, Int] {
  def param1 = T { "Param Value: " + crossValue }
  def param2 = T { "Param Value: " + crossValue2 }
}

```

Cross modules can also be extended piecemeal with additional axes via `Cross.ArgN`:

```scala
    object myCross extends Cross[MyCrossModule]("a", "b")
    trait MyCrossModule extends Cross.Module[String] {
      def param1 = T { "Param Value: " + crossValue }
    }

    object myCrossExtended extends Cross[MyCrossModuleExtended](("a", 1), ("b", 2))
    trait MyCrossModuleExtended extends MyCrossModule with Cross.Module2[String, Int] {
      def param2 = T{ "Param Value: " + crossValue2 }
    }

    object myCrossExtendedAgain extends Cross[MyCrossModuleExtendedAgain](("a", 1, true), ("b", 2, false))
    trait MyCrossModuleExtendedAgain extends MyCrossModuleExtended with Cross.Module3[String, Int, Boolean] {
      def param3 = T{ "Param Value: " + crossValue3 }
    }
```

So you can easily take a `CrossScalaModule` which is `Cross.Module[String]`, and mix in another say `Cross.Arg2[String]` if you want to cross-build it against different versions of some library as well

## Motivation

1. Reducing the boilerplate necessary to define a cross module: the `(val crossScalaVersion: String)` binding was always pretty awkward, and is pure boilerplate since the user ~never ends up referring to the `crossScalaVersion` value

2. Mill defines modules as `trait`s that get instantiated as `object`s. `class`es basically never come into the picture, *except* when defining `Cross[Module]`s. This change lets those use `trait`s too, making the framework more regular overall.

3. Make cross-module definition somewhat type safe, so we're not throwing `Any`s into the `Cross` constructor and getting weird explosions when we pass in a `Seq[String]` forgetting the `: _*`

## Implementation

1. Introduce a new trait `Cross.Module[V] extends mill.define.Module{ def crossValue: V }` that cross-modules can implement to support trait-based `Cross[T]` definitions.

2. Update the `Cross`/`Cross.Factory` to recognize when the type given to `Cross[T]` is a `trait` instead of a `class`, and if so swap the generated code from `new $tpe(..$argTupleValues)` to `new $tpe{ def crossValue = $v }`

4. Update the built-in cross modules `CrossScalaModule`/`CrossSbtModule`/`CrossScalaModule.Base` to implement `Cross[String]` by default, so the user doesn't need to think about this. Though anyone defining their own cross-trait (as a one-off or as a re-usable helper) would still need to make sure they extend `Cross.Module[T]` with the appropriate `T`

5. I took the opportunity to simplify the existing `Cross.Factory` macros, as well as replacing `mill.define.Ctx.crossInstances` with `crossValues` to support `CrossScalaVersionRanges` without needing to jump through hoops in the macro

## Notes

2. Although type-safety is greatly improved, there still is a bit of sloppiness in `Cross#apply(arg0: Any, args: Any*)`. It should be possible to improve this using the same macro technique we use in the `Cross` constructor, but I was hitting issues with Scala 2 macros and type inference misbehaving for nested Cross modules. For now we can leave that for future work

3. I expect most code can just use `crossValue` directly. But if anyone really needs to give it a name (e.g. if they have multiple nested cross modules and they need to refer to each one's value) it's relatively easy to go `def myNamedValue = crossValue` and then use `myNamedValue` after that. If `crossValue` is a tuple, then destructuring via `val (crossScalaVersion, crossPlayVersion) = crossValue` works as well

4. Doing a hard cut over to the new logic seems like the best option v.s. keeping various compatibility shims around:
    1. If we keep `Cross[T]` unchanged and introduce a new `Cross.Of[T]` for the new implementation, then people with existing `Cross[T]`s will face silent misbehavior due to https://github.com/com-lihaoyi/mill/pull/2347 causing sources and test-sources not to get picked up properly
    2. If we move the existing `Cross[T]` implementation to `Cross.Old[T]`, and make the new implementation `Cross[T]`, then this only marginally reduces migration work (people still need to manually update every call-site to `Cross.Old`) while greatly increasing complexity (both in user code may now have two different styles of cross-module floating around, and in Mill code which needs 3 due to two concrete implementations + an abstract base class)
    3. If we immediately kill the old logic, nobody gets silent misbehavior, everyone gets a nice compile error on how to upgrade (we can customize it with detailed instructions), we avoid having multiple cross-module implementations.

For some reason the `compileError` macro doesn't properly capture the custom error messages, but if I manually swap back to an old-style cross module in the test suite it gives me the following error message:

```
[error] /Users/lihaoyi/Github/mill/main/test/src/mill/util/TestGraphs.scala:269:31: 
[error] Cross type MyCross must be trait, not a class. Please change:
[error] 
[error]   class MyCross(scalaVersion: String, platform: String)
[error] 
[error] To:
[error] 
[error]   trait MyCross extends Cross.Module[(String, String)]{
[error]     val (scalaVersion, platform) = crossValue
[error]   }
[error] 
[error] You also no longer use `: _*` when instantiating a cross-module:
[error] 
[error]   Cross[MyCross](values:_*)
[error] 
[error] Instead, you can pass the sequence directly:
[error] 
[error]   Cross[MyCross](values)
[error] 
[error] Note that the `millSourcePath` of cross modules has changed in
[error] Mill 0.11.0, an no longer includes the cross values by default.
[error] If you have `def millSourcePath = super.millSourcePath / os.up`,
[error] you may remove it. If you do not have this definition, you can
[error] preserve the old behavior via `def millSourcePath = super.millSourcePath / crossValue`
[error] 
[error]     object cross extends mill.Cross[MyCross](crossMatrix:_*)
[error]                               ^
[error] two errors found
```

## Testing

1. All existing tests pass, modified to use the new syntax

2. Added `mill.eval.CrossTests.nonStringCross` and `mill.eval.CrossTests.crossExtension` to exercise those code paths in the unit test suite

3. Added additional `MacroErrorTests` to ensure that mis-typed cross keys or invalid cross types raises the appropriate compile error

4. I moved `integration.feature[cross]` to `example.misc[6-cross-module-axes]`, modified the test to exercise the non-string cross-key code path w.r.t. CLI invocation, and cross-module extension code path using `extends Cross.Arg3[T]`

### CODE REVIEW

File: scalanativelib/test/src/mill/scalanativelib/HelloNativeWorldTests.scala [hunk 1]
```diff
@@ -33,11 +39,10 @@ object HelloNativeWorldTests extends TestSuite {
       scalaNative <- Seq(scalaNative04, "0.4.9")
       mode <- List(ReleaseMode.Debug, ReleaseMode.ReleaseFast)
       if !(ZincWorkerUtil.isScala3(scala) && scalaNative == scalaNative04)
-    } yield (scala, scalaNative, mode)
+    } yield (scala, scalaNative, mode: ReleaseMode)
```
Comment (lihaoyi) [inline scalanativelib/test/src/mill/scalanativelib/HelloNativeWorldTests.scala:42]: Needing this type annotation is a limitation of type inference with the complicated `forSome` type we use in `Cross.Of`, where sub-types of the expected type are not properly widened. Providing an explicit annotation to give it the exact matching type seems to fix it

File: example/basic/11-scala-combined/bar/test/src-3/BarVersionSpecificTests.scala [hunk 2]
```diff
@@ -3,7 +3,7 @@ import utest._
 object BarVersionSpecificTests extends TestSuite {
   def tests = Tests {
     test("test") {
-      assert(BarVersionspecific.text().contains("3.x"))
+      assert(BarVersionSpecific.text().contains("3.x"))
```
Comment (lihaoyi) [inline example/basic/11-scala-combined/bar/test/src-3/BarVersionSpecificTests.scala:6]: I don't know why this wasn't blowing up before, but it's blowing up now, so I fixed it

**Comment by lolgab** [comment]
I love that we are getting rid of that annoying `: _*` 😍

**Comment by lolgab** [comment]
If we want to swap `Cross` and `Cross.Of` we could start to add a `Cross.Of` alias to `Cross` in Mill 0.10, enable deprecation warnings () by default and deprecate the current `Cross`, then the migration guide for Mill 0.11 should ask to fix all the deprecation warnings in 0.10 before migrating to 0.11. This is similar to what Scala.js did in the 0.6 -> 1 migration, deprecate APIs and ask users to fix all the deprecations before updating.

I would switch `Cross` and `Cross.Of` so new mill code will have the nicer/shorter syntax.

**Comment by lihaoyi** [comment]
Swapping `Cross` and `Cross.Of` (maybe call it `Cross.Old`?) could also have positive migration *benefits*, rather than downsides: 

1. We are already breaking everyone's non-`CrossScalaModule` cross-builds in https://github.com/com-lihaoyi/mill/pull/2347, while leaving their `CrossScalaModule` still working. This breakage is largely silent: people's `millSourcePath` will change, their `sources` will be empty, compilation will trivially succeed on empty sources, their jars will be created successfully (empty), their test suite `millSourcePath` will change and `.compile` and `.test` will succeed trivially since no tests were found, etc.

3. By making `Cross[T]` type-safe and require a `Cross.Module[T]`, we force all existing non-`CrossScalaModule`s cross-builds to immediately be compilation errors, rather than silent misbehaviors. That will force people to inspect each one and take some manual action before it can compile, either migrating to the new `trait`-based `Cross.Module`s or changing `Cross` to `Cross.Old`. We could potentially keep all the `Cross.Old`s working un-changed, e.g. reverting the https://github.com/com-lihaoyi/mill/pull/2347 changes for `Cross.Old`s, so once people add the `.Old` suffix things will continue to work as they were before, and they can migrate to the improved `Cross[T]` syntax at their leisure

**Comment by lihaoyi** [comment]
Another possibility is that we just drop the old cross-module logic entirely, without compatibility shims like `Cross.Old`:

1. We already know people need to update their custom `Cross` modules due to https://github.com/com-lihaoyi/mill/pull/2347, so causing some manual work is unavoidable.

2. We do want to force any un-changed cross's to be a compile-time breakage, since silent misbehavior is even worse. That means at the very least, people go through their code and update `Cross` to `Cross.Old` where necessary

3. Given that we're making things a compile-time breakage, requiring manual updating of each non-`CrossScalaModule` use-site of `Cross`, then all the `Cross.Old` shim lets people do is replace a bit of trivial work (replacing the `class Foo(x: Y)` with a `trait Foo{ def x: Y = crossValue }`) with a bit of even more trivial work (replacing `Cross` with `Cross.Old`)

4. The downside of providing `Cross.Old` shims is increased complexity both within the Mill codebase (now we have two cross implementations!) and in downstream codebases, which may be in half-migrated states.

5. For the vast majority of build code, I expect it to be using `CrossScalaModule`, and would be entirely affected by this change

Given that, I'm inclined to just drop the old un-typed `Cross` implementation entirely, and force a switch to the new one.

File: integration/feature/dynamic-cross-module/repo/build.sc [hunk 3]
```diff
@@ -1,10 +0,0 @@
-import mill._, scalalib._
```
Comment (lihaoyi) [inline integration/feature/dynamic-cross-module/repo/build.sc:1]: Deleted this guy because it's basically a duplicate of `example/misc/5-dynamic-cross-module/`

**Comment by lihaoyi** [comment]
@lefou this should be ready for you to look at. All tests are green, and I think the code and PR description is in merge-ready state

**Comment by lefou** [comment]
Please give me some more time for the review. I just glimpsed at comments. One issue I can think of is, that the requirement to expose the cross parameters as typed `def` is blocking some re-use of traits like `CrossScalaModule` (which already binds the `crossValue` type to a String) in a multi-dimensional cross module. As we need to mix traits with conflicting type bounds for `crossValue`.

**Comment by lihaoyi** [comment]
@lefou OK, take your time.

Yes it's true that now you can only inherit a single `Cross.Module[T]` type T, whereas previously cross modules were not really typed so you could do whatever as long as the constructor parameters are given

One way I'd look at it is that you can in general make the new approach equivalent to the old approach by always moving with `with Cross.Module[T]` to the "final" `trait`s, the ones that are immediately passed to the `Cross[T]` macro. That gives a level of verbosity approximately equal where we need to specify today, perhaps a bit more, but guarantees you won't have any `Cross.Module[T]` type conflicts since every `trait` only inherits from `Cross.Module[T]` in exactly one place.

The only limitation with the *"only inherit from `Cross.Module[T]` at the very end"* approach is that it cannot be done for external types a user does not control that already inherit from `Cross.Module`, e.g. `CrossScalaModule`. This could be solved if we split up `CrossScalaModule` to have some base trait `CrossScalaModuleOps` or something that does not inherit from `Cross.Module` for the rare scenarios where people want to use it in a CrossModule of a different type. Then the common case where we do want `Cross.Module[String]` can continue to be easy, and for people who want some other `Cross.Module` type then `CrossScalaModuleOps` can let them specify it themselves

**Comment by lefou** [comment]
> @lefou OK, take your time.
> 
> Yes it's true that now you can only inherit a single `Cross.Module[T]` type T, whereas previously cross modules were not really typed so you could do whatever as long as the constructor parameters are given
> 
> One way I'd look at it is that you can in general make the new approach equivalent to the old approach by always moving with `with Cross.Module[T]` to the "final" `trait`s, the ones that are immediately passed to the `Cross[T]` macro. That gives a level of verbosity approximately equal where we need to specify today, perhaps a bit more, but guarantees you won't have any `Cross.Module[T]` type conflicts since every `trait` only inherits from `Cross.Module[T]` in exactly one place.
> 
> The only limitation with the _"only inherit from `Cross.Module[T]` at the very end"_ approach is that it cannot be done for external types a user does not control that already inherit from `Cross.Module`, e.g. `CrossScalaModule`. This could be solved if we split up `CrossScalaModule` to have some base trait `CrossScalaModuleOps` or something that does not inherit from `Cross.Module` for the rare scenarios where people want to use it in a CrossModule of a different type. Then the common case where we do want `Cross.Module[String]` can continue to be easy, and for people who want some other `Cross.Module` type then `CrossScalaModuleOps` can let them specify it themselves. But I expect this use case to be rare enough we might not need to cater for it

What I like: We get some type safety, which is nice and prohibits some error conditions.

Also, we get rid of the ugly `: _*` cast (but we could also solve this directly in the current approach).

What I don't like so much: We introduce some convention of only placing the `Cross.Module[T]` when defining the actual module. This will never be obvious to users nor providers of abstractions and plugins. And I'd argue there will be some cross module traits which already inherit `Cross.Module[T]` in the wild. Even when tested with the expected setup, everything seems to work except someone need to bring another cross-coordinate in. And the workaround by introducing some `CrossScalaModuleOps` is something I would avoid at all costs. This is exactly what makes the difference between a slightly structured build script versus a small piece of well (or not so well) crafted software, and either the reader gets lost or the writer switches to trial-and-error mode.

Personally, I never had issues with the inconsistent use of a `class` when defining cross modules. Do you see any chance that we enforce or at least check that `Cross.Module[T]` is only used when defining actual cross module? 

Can we somehow split the types of the various cross dimensions, so that we have a dedicated trait for each dimension? A `CrossScalaModule` could implement `Cross.ModuleFirst[String]` and later another dimension could be merged with `Cross.ModuleSecond[T]`. (The names are only choosen to make the concept clear)?

**Comment by lihaoyi** [comment]
> Can we somehow split the types of the various cross dimensions, so that we have a dedicated trait for each dimension? A CrossScalaModule could implement Cross.ModuleFirst[String] and later another dimension could be merged with Cross.ModuleSecond[T]. (The names are only choosen to make the concept clear)?

This sounds possible. Let me experiment with this and see what I come up with. We can even has things like 

```scala 
type Cross.Module2[T1, T2] = Cross.Module[T1] with Cross.Module.Second[T2]
```

so we'll have both the conciseness and the flexibility

**Comment by lefou** [comment]
> > Can we somehow split the types of the various cross dimensions, so that we have a dedicated trait for each dimension? A CrossScalaModule could implement Cross.ModuleFirst[String] and later another dimension could be merged with Cross.ModuleSecond[T]. (The names are only choosen to make the concept clear)?
> 
> This sounds possible. Let me experiment with this and see what I come up with. We can even has things like
> 
> ```scala
> type Cross.Module2[T1, T2] = Cross.Module[T1] with Cross.Module.Second[T2]
> ```
> 
> so we'll have both the conciseness and the flexibility

That would be cool. If we get this to work, we can make it also less verbose, as there is no longer the need for the user to define the `crossValue`. Instead, as each dimension binding comes from another trait, a `CrossScalaModule` could already bind `crossValueFirst` to the scala version. 

(I'd expect to see some wrapper constructs sooner or later, which lifts cross-modules into another dimentsion, haha)

File: main/core/src/mill/define/Cross.scala [hunk 4]
```diff
@@ -1,94 +1,161 @@
...
+           |You also no longer use `: _*` when instantiating a cross-module:
+           |
+           |  Cross[${tpe.typeSymbol.name}](values:_*)
+           |
+           |Instead, you can pass the sequence directly:
+           |
+           |  Cross[${tpe.typeSymbol.name}](values)
+           |
+           |Note that the `millSourcePath` of cross modules has changed in
+           |Mill 0.11.0, an no longer includes the cross values by default.
```
Comment (lolgab) [inline main/core/src/mill/define/Cross.scala:151]:
```suggestion
           |Mill 0.11.0, and no longer includes the cross values by default.
```

File: integration/feature/cross/repo/build.sc [hunk 5]
```diff
@@ -4,27 +4,28 @@ import mill.define.{Cross, Module}
...
+  def param1 = T { crossValue }
+  def param2 = T { crossValue2 }
   def path = T { PathRef(millSourcePath) }
 }
 
 object topCrossU extends Cross[TopCrossU]("a", "b")
-class TopCrossU(p1: String) extends Module {
-  override def millSourcePath = super.millSourcePath / p1
-  def param1 = T { p1 }
+trait TopCrossU  extends Cross.Module[String] {
```
Comment (lolgab) [inline integration/feature/cross/repo/build.sc:20]:
```suggestion
trait TopCrossU extends Cross.Module[String] {
```

File: scalalib/src/mill/scalalib/CrossScalaModule.scala [hunk 6]
```diff
@@ -33,12 +33,13 @@ object CrossScalaModule {
...
-  trait Base extends mill.Module {
-    def crossScalaVersion: String
+  trait Base extends mill.Cross.Module[String] {
+    def crossScalaVersion: String = crossValue
+    def crossPathSegments = List(crossScalaVersion)
     private def wrapperSegments0 = millModuleSegments.parts
     trait CrossScalaModule extends mill.scalalib.CrossScalaModule {
       override def wrapperSegments = wrapperSegments0
-      def crossScalaVersion = Base.this.crossScalaVersion
+      def crossValue = Base.this.crossScalaVersion
```
Comment (lefou) [inline scalalib/src/mill/scalalib/CrossScalaModule.scala:43]: Isn't `crossValue` already defined in inherited Cross.Module (via CrossScalaModule)?

Comment (lihaoyi) [reply scalalib/src/mill/scalalib/CrossScalaModule.scala:43]: Yes, but this is a bit of an unusual case: the actual `Cross.Module` that gets passed to `Cross` is `CrossScalaModule.Base`. These `CrossScalaModules` nested within it are just proxies that share the `crossValue` of the `Base` trait, so we don't need to repeat the `extends Cross[...](...)` for every single submodule

So for these inner `CrossScalaModule`s, the call to `crossValue` just forwards to the `crossValue` of the enclosing `CrossScalaModule.Base`

We could also split up `CrossScalaModule` so there's a `CrossScalaModule0` that foes not have `Cross.Module` mixed in, and then do the forwarding in `def crossScalaVersion` instead. I don't have a strong opinion either way

Comment (lefou) [reply scalalib/src/mill/scalalib/CrossScalaModule.scala:43]: Huh, hard to grasp. I guess understanding this is all about getting how `CrossScalaModule.Base` is supposed to work/used, which isn't obvious from the code itself. We should add some doc to `CrossScalaModule.Base`, describing the concept. An example (or link to it) says probably more than many words.

Comment (lihaoyi) [reply scalalib/src/mill/scalalib/CrossScalaModule.scala:43]: Yeah I'm not totally happy with it, but it's in the examples which I hope to include in the docs. 

In general I'd hope this kind of "base"/"nested" thing to be generic and not tied to `ScalaModule`, but for now this trades off some simplicity for some much needed convenience to defining cross-built Scala projects

Comment (lihaoyi) [reply scalalib/src/mill/scalalib/CrossScalaModule.scala]: @lefou I think I've come to a reasonable solution here: 

1. The `CrossScalaModule.Base`/`CrossScalaModule` pairing has been replaced by a more general `Cross.ModuleN`/`InnerCrossModuleN` pairing. Thus any `Cross.ModuleN` can contain `InnerCrossModuleN`s that share the same set of `crossValueN`s

2. Removed the `Cross.Arg[T]` traits, leaving just `Cross.ModuleN`, to allow the `InnerCrossModuleN`s to work properly

Essentially, now "propagate cross values to child modules" is a generic capability that all `Cross.Module`s have, not just `CrossScalaModule`. It's marginally more verbose at the use site (`extends CrossScalaModule with InnerCrossModule` rather than just `extends CrossScalaModule`) but overall should be a reasonable compromise between conciseness, simplicity, and genericity.

File: integration/feature/dynamic-cross-module/repo/build.sc (hunk 3 above)
Comment (lefou) [reply integration/feature/dynamic-cross-module/repo/build.sc:1]: Are examples also run as integration test?

**Review by lefou — COMMENTED** [review]
Looks good to me. Nice work! What about those integration tests you removed? Are they redundant to some others?

**Comment by lihaoyi** [comment]
> Looks good to me. Nice work! What about those integration tests you removed? Are they redundant to some others?

Yes, the `dynamic-cross-modules` integration test duplicates the existing example test of the same name, while the other one does the same thing as the `cross-module-axes` example test. The examples are all executable (they just use a pseudo-bash DSL rather than Scala to define the assertions, adding readability for educational purposes) so I removed the integration tests that duplicate things already covered in examples
