### ISSUE TITLE
java.util.StringTokenizer.asIterator() only exists in Java 9

### ISSUE THREAD

**Issue by He-Pin** [com-lihaoyi/mill#4168]
Mill version 0.12.4
```
rror: Exception in thread "main" java.lang.NoSuchMethodError: java.util.StringTokenizer.asIterator()Ljava/util/Iterator;
	at mill.eval.Plan$.splitEnclosing$1(Plan.scala:52)
	at mill.eval.Plan$.$anonfun$assignOverridenTaskSegments$3(Plan.scala:58)
	at scala.collection.immutable.List.map(List.scala:247)
	at scala.collection.immutable.List.map(List.scala:79)
```
This `asInterator` method only exists from Java 9.

Found this in https://github.com/com-lihaoyi/fastparse/pull/324
When upgrade from 0.12.3 to 0.12.4

**Comment by lihaoyi** [comment]
Mill 0.12.x only supports java 11 and above
