### ISSUE TITLE
Regression: No given instance of type upickle.default.ReadWriter was found

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#6767]
A project building fine with Mill `1.1.0` errors with snapshot release Mill `1.1.0-47-acdf63`.

```console
> MILL_VERSION="1.1.0-47-acdf63" mill __.compile
build.mill-67] compile compiling 89 Scala sources to out/mill-build/compile.dest/classes ...
build.mill-67] [error] mill-build/src/comfisbuild/VaadinMavenModule.scala:168:4
build.mill-67]   }
build.mill-67]    ^
build.mill-67] No given instance of type upickle.default.ReadWriter[(jar : mill.PathRef, assembly : mill.PathRef)] was found for parameter rw of method apply in object Task.
build.mill-67] I found:
build.mill-67] 
build.mill-67]     upickle.default.ReadWriter.join[(jar : mill.PathRef, assembly : mill.PathRef)](
build.mill-67]       upickle.default.superTypeReader[
build.mill-67]         (jar : mill.PathRef, assembly : mill.PathRef), V](
build.mill-67]         new scala.runtime.TupleMirror(2).$asInstanceOf[
build.mill-67]           
build.mill-67]             scala.deriving.Mirror.Product{
build.mill-67]               type MirroredMonoType = (jar : mill.PathRef, assembly : mill.PathRef)
build.mill-67]                 ;
build.mill-67]                 type MirroredType = (jar : mill.PathRef, assembly : mill.PathRef);
build.mill-67]                 type MirroredLabel = ("NamedTuple" : String);
build.mill-67]                 type MirroredElemTypes = (mill.PathRef, mill.PathRef);
build.mill-67]                 type MirroredElemLabels = (("jar" : String), ("assembly" : String))
build.mill-67]             }
build.mill-67]           
build.mill-67]         ],
build.mill-67]       upickle.default.SeqLikeReader[C, T], ???, ???),
build.mill-67]     ???)
build.mill-67] 
build.mill-67] But method SeqLikeReader in trait Readers does not match type upickle.default.Reader[V].
build.mill-67] 
build.mill-67] [error] one error found
67/72, 1 FAILED] mill __.compile 21s
build.mill-67] [error] compile Compilation failed
```

This is the task definition:

```scala
  def mvnPackage: Task.Simple[(jar: PathRef, assembly: PathRef)] = Task {
    BuildCtx.withFilesystemCheckerDisabled {
      mvnTask(Task.Anon {
        Args("package")
      })()
      val a = vaadinMavenConfig().artifact
      val assemblyFile = vaadinMavenGenWorker().modulePath / "target" / s"${a.id}-${a.version}.jar"
      // spring-boot:repackage produces a single jar, with all dependencies in it
      // but our yajsw-launcher does not handle it, so we use the plain jar
      val jarFile = vaadinMavenGenWorker().modulePath / "target" / s"${a.id}-${a.version}.jar.original"
      assert(os.exists(jarFile))
      assert(os.exists(assemblyFile))
      (PathRef(jarFile), PathRef(assemblyFile))
    }
  }
```

**Comment by lefou** [comment]
Same for `1.1.0-10-fec938`.

**Comment by lihaoyi** [comment]
Can you try `import upickle.implicits.namedTuples.default.given`? Might be some type inference implicit resolution thing

**Comment by lefou** [comment]
That worked.

**Comment by lefou** [comment]
I guess, this is not a bug then, but I don't understand why it worked with Mill `1.1.0` without the explicit import.
