### ISSUE TITLE
`--import` with `repl` does not actually seem to put it on the REPL compiler classpath

### ISSUE THREAD

**Issue by bishabosha** [com-lihaoyi/mill#6730]
in mill 1.1.0, example from Hands-on Scala programming chapter 9

```bash
./mill --import "org.commonmark:commonmark:0.26.0" repl

Welcome to Scala 3.8.1 (21.0.9, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> sys.props("java.class.path").split(":").filter(_.contains("commonmark"))
val res0: Array[String] = Array(
  "/...../out/console.dest/commonmark-0.26.0-5f553c45-module-info-stripped-jar"
)

scala> val parser = org.commonmark.parser.Parser.builder().build()
-- [E008] Not Found Error: -----------------------------------------------------
1 |val parser = org.commonmark.parser.Parser.builder().build()
  |             ^^^^^^^^^^^^^^
  |             value commonmark is not a member of org
1 error found
```

**Comment by lihaoyi** [comment]
Seems like a new breakage caused by https://github.com/com-lihaoyi/mill/pull/6455's introduction of `stripModuleInfo`, which somehow causes the jar to not get properly processed by the Scala REPL
